services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: quiro-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_EMAILS=${ALLOWED_EMAILS}
    networks:
      - consultorio-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: quiro-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    networks:
      - consultorio-network
    restart: always

networks:
  consultorio-network:
    driver: bridge
